# Generated by Django 5.1.6 on 2025-09-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('ADMIN', 'Admin'), ('DEPT_OFFICER', 'Department Officer')], default='CITIZEN', max_length=20),
        ),
    ]
