# Generated by Django 5.1.6 on 2025-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
