# Generated by Django 5.1.6 on 2025-09-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0007_alter_department_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='severity',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
