# Generated by Django 5.1.6 on 2025-09-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0008_issue_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='custom_category',
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
    ]
