# Generated by Django 5.1.6 on 2025-09-15 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0009_remove_issue_custom_category_alter_issue_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('MISCLASSIFICATION', 'Misclassification'), ('MULTI_DEPT_NEXT_STEP', 'Multi-Dept Next Step')], max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hygiene.department')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hygiene.issue')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
