# Generated by Django 5.1.6 on 2025-09-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0010_departmentnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentnotification',
            name='department',
            field=models.ForeignKey(limit_choices_to={'name__in': ['HYGIENE', 'ROADS', 'ELECTRICITY', 'WATER', 'SAFETY', 'INFRA']}, on_delete=django.db.models.deletion.CASCADE, to='hygiene.department'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('HYGIENE', 'Hygiene & Sanitation'), ('ROADS', 'Road & Transport'), ('ELECTRICITY', 'Streetlights & Electricity'), ('WATER', 'Water Supply & Drainage'), ('SAFETY', 'Safety & Emergency Hazards'), ('INFRA', 'Public Infrastructure')], default='HYGIENE', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__in': ['HYGIENE', 'ROADS', 'ELECTRICITY', 'WATER', 'SAFETY', 'INFRA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hygiene.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__in': ['HYGIENE', 'ROADS', 'ELECTRICITY', 'WATER', 'SAFETY', 'INFRA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hygiene.department'),
        ),
    ]
