# Generated by Django 5.1.6 on 2025-09-17 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0011_alter_departmentnotification_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='video',
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departmentnotification',
            name='department',
            field=models.ForeignKey(limit_choices_to={'name__in': ['HYGIENE', 'ROADS', 'ELECTRICITY', 'WATER', 'SAFETY', 'INFRA', 'OTHER']}, on_delete=django.db.models.deletion.CASCADE, to='hygiene.department'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('HYGIENE', 'Hygiene & Sanitation'), ('ROADS', 'Road & Transport'), ('ELECTRICITY', 'Streetlights & Electricity'), ('WATER', 'Water Supply & Drainage'), ('SAFETY', 'Safety & Emergency Hazards'), ('INFRA', 'Public Infrastructure'), ('OTHER', 'Other')], default='HYGIENE', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue', to='hygiene.department'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolution_proof',
            field=models.FileField(blank=True, null=True, upload_to='resolutions/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Approval'), ('RESOLVED', 'Resolved'), ('REASSIGNED', 'Reassigned'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__in': ['HYGIENE', 'ROADS', 'ELECTRICITY', 'WATER', 'SAFETY', 'INFRA', 'OTHER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hygiene.department'),
        ),
        migrations.CreateModel(
            name='SolveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_requests', to='hygiene.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
