# Generated by Django 5.1.6 on 2025-09-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0012_remove_issue_address_remove_issue_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='issues/'),
        ),
    ]
