# Generated by Django 5.1.6 on 2025-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0013_issue_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
