# Generated by Django 5.1.6 on 2025-09-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0014_issue_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='duplicate_count',
            field=models.IntegerField(default=0),
        ),
    ]
