# Generated by Django 5.1.6 on 2025-09-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0015_issue_duplicate_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
