# Generated by Django 5.2.3 on 2026-02-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0016_issue_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='community_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_flagged_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Approval'), ('RESOLVED', 'Resolved'), ('REASSIGNED', 'Reassigned'), ('FLAGGED', 'Flagged for Review'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
