# Generated by Django 5.2.3 on 2026-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0018_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='volunteer_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
