# Generated by Django 5.1.6 on 2026-08-21 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0019_issue_volunteer_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='volunteer_deadline',
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='location_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority_score',
            field=models.IntegerField(db_index=True, default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('ADMIN', 'Admin'), ('DEPT_OFFICER', 'Department Officer'), ('DEPT_EMPLOYEE', 'Department Employee')], default='CITIZEN', max_length=20),
        ),
    ]
